### ISSUE TITLE
Support for few devices of the same type

### ISSUE THREAD

**Issue by v1993** [v1993/evdevhook#1]
I don't have few devices of the same type and don't know how to support those (do their reported names differ?). If someone have two or more pairs of joycons, please write here. Your help will be greatly appreciated!

**Comment by v1993** [comment]
Their reported names don't differ. It shouldn't be too hard to add support for few devices with same name connected at once (as long as they are all handled by the same instance of evdevhook).

**Comment by qurious-pixel** [comment]
Two devices with the same device name, will cause the newer one to take precedence based on time stamp. Device uniq identifier (mac address for example) could be used to support multiple devices.

**Comment by v1993** [comment]
Issue is that there isn't a unique ID quite always. I have a plan how to implement this, just didn't got to do it yet :)

**Comment by foresto** [comment]
The python libudev wrapper [uses](/pyudev/pyudev/blob/master/src/pyudev/device/_device.py#L614) the result of [udev_device_get_devpath()](https://www.freedesktop.org/software/systemd/man/udev_device_get_devpath.html) to uniquely identify a single device. Wouldn't that work here?

**Comment by loveisfoss** [comment]
udev rule I use for DualSense:
Create a file: /etc/udev/rules.d/50-ds-motion.rules
`ATTRS{name}=="Wireless Controller Motion Sensors", OWNER="username", `MODE="0660"
evdevhook can now connect without the need for extra chmod command.

**Comment by v1993** [comment]
About devpath - it does not meaningfully describe what device is. It works as an identifier, sure, but this isn't a problem anyways.

There aren't really any blockers about this, it's just that I didn't get to do it yet.

**Comment by v1993** [comment]
Implemented in [evdevhook2](https://github.com/v1993/evdevhook2).
