### ISSUE TITLE
Does `evdevhook` need `joycond` to work?

### ISSUE THREAD

**Issue by aeghn** [v1993/evdevhook#12]
Thank you for creating this wonderful application. I am using `evdevhook` with linux 5.16.12-arch1-1 and I am having some problems like disconnecting from my computer. I found that if I enable `joycond` it will disconnect after 15 minutes but if I just use evdevhook it will disconnect after 2 or 3 minutes so I was wondering if it is necessary to use joycond.

**Comment by aeghn** [comment]
I also commented here: https://github.com/DanielOgorchock/linux/issues/33#issuecomment-1059734758

**Comment by v1993** [comment]
No, joycond is a completely separate application. Some of its functionality overlaps with evdevhook, but that's about it.

Linux is not very good with keeping connection to joycons. For me, they stay connected fine until I start using rumble, but it will vary per driver and bluetooth adapter.

**Comment by aeghn** [comment]
> For me, they stay connected fine until I start using rumble

Yes, I'm having this problem too, especially when I'm using the pro controller and my bluetooth headset at the same time. My bluetooth headset and controller will disconnect at the same time, and bluetooth service will be unresponsive, when I try `bluetoothctl devices` it will stop my whole system from responding.
