### ISSUE TITLE
How can i install this?

### ISSUE THREAD

**Issue by letsgoawaydev** [v1993/evdevhook#14]
Sorry, i am new to linux and I'm not the best at this stuff

**Comment by Andrews2024** [comment]
New to it too, but here's how I got it installed:
1) Installed dkms module using the link in the README (instructions provided)
2) Installed the dependencies using the command provided in the README
3) Cloned the repo with `git clone https://github.com/v1993/evdevhook`
4) `cd evdevhook`
5)  Don't know if you need this, but I did it when building Dolphin on my computer: `git submodule update --init`
6) `mkdir Build && cd Build`
7) `cmake ..`
8) `make -j$(nproc)`
9) `sudo make install`

This is on Ubuntu 22.04. Hope this helps!

**Comment by v1993** [comment]
Closing as part of repo archiving.
