### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by Phononenom** [v1993/evdevhook#15]
Hi, I am running into errors when attempting to actually build evdevhook. 
I am running Ubuntu Bionic 18.04 L4T from switchroot on a nintendo switch.

All dependencies, except for nlohmann, were available through my native repos. nlohmann was added in via vcpkg to make the required version number, and the vcpkg toolchain was used to make the build files.

Build files were made without problem, but I am running into make errors immediately when compiling

here is a verbose dump 

/usr/bin/cmake -S/home/phononenom/evdevhook -B/home/phononenom/evdevhook/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/phononenom/evdevhook/build/CMakeFiles /home/phononenom/evdevhook/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/phononenom/evdevhook/build'
make  -f CMakeFiles/evdevhook.dir/build.make CMakeFiles/evdevhook.dir/depend
make[2]: Entering directory '/home/phononenom/evdevhook/build'
cd /home/phononenom/evdevhook/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/phononenom/evdevhook /home/phononenom/evdevhook /home/phononenom/evdevhook/build /home/phononenom/evdevhook/build /home/phononenom/evdevhook/build/CMakeFiles/evdevhook.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/phononenom/evdevhook/build'
make  -f CMakeFiles/evdevhook.dir/build.make CMakeFiles/evdevhook.dir/build
make[2]: Entering directory '/home/phononenom/evdevhook/build'
[ 25%] Building CXX object CMakeFiles/evdevhook.dir/src/main.cpp.o
/usr/bin/c++ -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -isystem /usr/include/libevdev-1.0 -isystem /usr/include/glibmm-2.4 -isystem /usr/lib/aarch64-linux-gnu/glibmm-2.4/include -isystem /usr/include/glib-2.0 -isystem /usr/lib/aarch64-linux-gnu/glib-2.0/include -isystem /usr/include/sigc++-2.0 -isystem /usr/lib/aarch64-linux-gnu/sigc++-2.0/include -isystem /usr/include/giomm-2.4 -isystem /usr/lib/aarch64-linux-gnu/giomm-2.4/include -isystem /home/phononenom/vcpkg/installed/arm64-linux/include -pthread -std=gnu++1z -MD -MT CMakeFiles/evdevhook.dir/src/main.cpp.o -MF CMakeFiles/evdevhook.dir/src/main.cpp.o.d -o CMakeFiles/evdevhook.dir/src/main.cpp.o -c /home/phononenom/evdevhook/src/main.cpp
/home/phononenom/evdevhook/src/main.cpp: In function ‘void {anonymous}::LoadConfig(std::istream&)’:
/home/phononenom/evdevhook/src/main.cpp:158:25: error: ‘class std::unordered_map<std::__cxx11::basic_string<char>, unsigned char>’ has no member named ‘contains’
    if (g_name_to_devidx.contains(name)) {
                         ^~~~~~~~
CMakeFiles/evdevhook.dir/build.make:75: recipe for target 'CMakeFiles/evdevhook.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/evdevhook.dir/src/main.cpp.o] Error 1
make[2]: Leaving directory '/home/phononenom/evdevhook/build'
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/evdevhook.dir/all' failed
make[1]: *** [CMakeFiles/evdevhook.dir/all] Error 2
make[1]: Leaving directory '/home/phononenom/evdevhook/build'
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
![errors](https://user-images.githubusercontent.com/64574232/164608984-16fe59a6-2779-424f-9bee-55001991b38e.png)

**Comment by v1993** [comment]
It's caused by an outdated core C++ library in that ubuntu version. Nothing I can do about this.

**Comment by v1993** [comment]
> Do you know what versions are needed?

Something around gcc 10.

> Would this be possible to compile, say in visual studio, vs using the terminal potentially?

Visual studio does not have linux support, VS Code just calls native compilers.

> Short of that, do you know of any other linux based solutions for passing motion data to cemuhook?

Joycond + joycond-cemuhook exist, but I'm not sure it would work on switch edition of linux kernel. Frankly, I'm not even sure if evdevhook would.

**Comment by Phononenom** [comment]
Thats odd, I do have g++-11 past 11.0.

![g++-11](https://user-images.githubusercontent.com/64574232/164771293-81286c26-8223-49f2-b7c5-04fae00795fd.png)

Its based on Nvidias edition of linux kernel, so while janky, has a bit of support. Even stranger, joycond is brought in early on this image for an xinput server to act as a mouse, but joycond-cemuhook is running into similar compiling errors. 

I guess its time to flash another image again haha. Thanks for the help

**Comment by Phononenom** [comment]
Wait, I forgot to set alternative for gcc when got the newer one. After setting my gcc and g++ to 11, I got new build errors

`phononenom@phononenom-laptop:~/evdevhook/build$ make VERBOSE=1
/usr/bin/cmake -S/home/phononenom/evdevhook -B/home/phononenom/evdevhook/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/phononenom/evdevhook/build/CMakeFiles /home/phononenom/evdevhook/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/phononenom/evdevhook/build'
make  -f CMakeFiles/evdevhook.dir/build.make CMakeFiles/evdevhook.dir/depend
make[2]: Entering directory '/home/phononenom/evdevhook/build'
cd /home/phononenom/evdevhook/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/phononenom/evdevhook /home/phononenom/evdevhook /home/phononenom/evdevhook/build /home/phononenom/evdevhook/build /home/phononenom/evdevhook/build/CMakeFiles/evdevhook.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/phononenom/evdevhook/build'
make  -f CMakeFiles/evdevhook.dir/build.make CMakeFiles/evdevhook.dir/build
make[2]: Entering directory '/home/phononenom/evdevhook/build'
[ 25%] Building CXX object CMakeFiles/evdevhook.dir/src/main.cpp.o
/usr/bin/c++ -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -isystem /usr/include/libevdev-1.0 -isystem /usr/include/glibmm-2.4 -isystem /usr/lib/aarch64-linux-gnu/glibmm-2.4/include -isystem /usr/include/glib-2.0 -isystem /usr/lib/aarch64-linux-gnu/glib-2.0/include -isystem /usr/include/sigc++-2.0 -isystem /usr/lib/aarch64-linux-gnu/sigc++-2.0/include -isystem /usr/include/giomm-2.4 -isystem /usr/lib/aarch64-linux-gnu/giomm-2.4/include -isystem /home/phononenom/vcpkg/installed/arm64-linux/include -pthread -std=gnu++20 -MD -MT CMakeFiles/evdevhook.dir/src/main.cpp.o -MF CMakeFiles/evdevhook.dir/src/main.cpp.o.d -o CMakeFiles/evdevhook.dir/src/main.cpp.o -c /home/phononenom/evdevhook/src/main.cpp
In file included from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:23,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from /usr/include/giomm-2.4/giomm.h:22,
                 from /home/phononenom/evdevhook/src/main.cpp:23:
/usr/include/glibmm-2.4/glibmm/variant.h:943:24: error: expected unqualified-id before ‘)’ token
  943 |   Variant<VariantBase>();
      |                        ^
/usr/include/glibmm-2.4/glibmm/variant.h:1004:25: error: expected unqualified-id before ‘)’ token
 1004 |   Variant< Variant<T> >();
      |                         ^
/usr/include/glibmm-2.4/glibmm/variant.h:1057:26: error: expected unqualified-id before ‘)’ token
 1057 |   Variant<Glib::ustring>();
      |                          ^
/usr/include/glibmm-2.4/glibmm/variant.h:1227:24: error: expected unqualified-id before ‘)’ token
 1227 |   Variant<std::string>();
      |                        ^
/usr/include/glibmm-2.4/glibmm/variant.h:1273:30: error: expected unqualified-id before ‘)’ token
 1273 |   Variant< std::pair<K, V> >()
      |                              ^
/usr/include/glibmm-2.4/glibmm/variant.h:1322:29: error: expected unqualified-id before ‘)’ token
 1322 |   Variant< std::vector<T> >()
      |                             ^
/usr/include/glibmm-2.4/glibmm/variant.h:1391:41: error: expected unqualified-id before ‘)’ token
 1391 |   Variant< std::vector<Glib::ustring> >();
      |                                         ^
/usr/include/glibmm-2.4/glibmm/variant.h:1517:39: error: expected unqualified-id before ‘)’ token
 1517 |   Variant< std::vector<std::string> >();
      |                                       ^
/usr/include/glibmm-2.4/glibmm/variant.h:1593:29: error: expected unqualified-id before ‘)’ token
 1593 |   Variant< std::map<K, V> >()
      |                             ^
/usr/include/glibmm-2.4/glibmm/variant.h:1666:33: error: expected unqualified-id before ‘)’ token
 1666 |   Variant<std::tuple<Types...>>()
      |                                 ^
In file included from /usr/include/glibmm-2.4/glibmm/variant.h:1729,
                 from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:23,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from /usr/include/giomm-2.4/giomm.h:22,
                 from /home/phononenom/evdevhook/src/main.cpp:23:
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:23:17: error: expected unqualified-id before ‘)’ token
   23 |   Variant<bool>()
      |                 ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:66:26: error: expected unqualified-id before ‘)’ token
   66 |   Variant<unsigned char>()
      |                          ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:109:19: error: expected unqualified-id before ‘)’ token
  109 |   Variant<gint16>()
      |                   ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:152:20: error: expected unqualified-id before ‘)’ token
  152 |   Variant<guint16>()
      |                    ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:195:19: error: expected unqualified-id before ‘)’ token
  195 |   Variant<gint32>()
      |                   ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:244:20: error: expected unqualified-id before ‘)’ token
  244 |   Variant<guint32>()
      |                    ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:287:19: error: expected unqualified-id before ‘)’ token
  287 |   Variant<gint64>()
      |                   ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:330:20: error: expected unqualified-id before ‘)’ token
  330 |   Variant<guint64>()
      |                    ^
/usr/include/glibmm-2.4/glibmm/variant_basictypes.h:373:19: error: expected unqualified-id before ‘)’ token
  373 |   Variant<double>()
      |                   ^
In file included from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:23,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from /usr/include/giomm-2.4/giomm.h:22,
                 from /home/phononenom/evdevhook/src/main.cpp:23:
/usr/include/glibmm-2.4/glibmm/variant.h:1738:1: error: no declaration matches ‘Glib::Variant<Glib::Variant<T> >::Variant()’
 1738 | Variant< Variant<T> >::Variant()
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:23,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from /usr/include/giomm-2.4/giomm.h:22,
                 from /home/phononenom/evdevhook/src/main.cpp:23:
/usr/include/glibmm-2.4/glibmm/variant.h:1013:12: note: candidate is: ‘Glib::Variant<Glib::Variant<T> >::Variant(GVariant*, bool)’
 1013 |   explicit Variant< Variant<T> >(GVariant* castitem, bool take_a_reference = false);
      |            ^~~~~~~~~~~~~~~~~~~~~
/usr/include/glibmm-2.4/glibmm/variant.h:996:7: note: ‘class Glib::Variant<Glib::Variant<T> >’ defined here
  996 | class Variant< Variant<T> > : public VariantContainerBase
      |       ^~~~~~~~~~~~~~~~~~~~~
CMakeFiles/evdevhook.dir/build.make:75: recipe for target 'CMakeFiles/evdevhook.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/evdevhook.dir/src/main.cpp.o] Error 1
make[2]: Leaving directory '/home/phononenom/evdevhook/build'
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/evdevhook.dir/all' failed
make[1]: *** [CMakeFiles/evdevhook.dir/all] Error 2
make[1]: Leaving directory '/home/phononenom/evdevhook/build'
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
`
![Screenshot from 2022-04-22 13-37-10](https://user-images.githubusercontent.com/64574232/164775000-20fd7ab6-3731-4a77-aaa7-5e52d5f7880c.png)
![Screenshot from 2022-04-22 13-37-27](https://user-images.githubusercontent.com/64574232/164775023-f72ff9c9-03e0-471e-b5cc-ffe304c563e7.png)
![Screenshot from 2022-04-22 13-38-32](https://user-images.githubusercontent.com/64574232/164775043-1a377e97-9cc2-406f-8eec-8d19455ad6b0.png)

If the C++ libraries are updated, how do I tackle this error? Thanks again

**Comment by v1993** [comment]
Not really sure what could be happening here, sorry. Also, please use ``` for multi-line code blocks.

**Comment by Phononenom** [comment]
It's all good, I figure it's time for a new image anyways. Thanks for all the help, and the heads up for editing

**Comment by v1993** [comment]
FYI - there are android cemuhook motion servers out there. You might have better time with those.

**Comment by Phononenom** [comment]
I've heard great things with android or with horizon os, I just use my raspberry pi and 3ds with linux often with the same projects, and the freedom and versatility a linux build brings wants me to keep it on here. Maybe I'll just make a small partition for that, or try bionic or fedora. Either way, I really do appreciate the help
