### ISSUE TITLE
DualSense mapping is wrong

### ISSUE THREAD

**Issue by v1993** [v1993/evdevhook#3]
Sadly, it seems that DualSense uses mapping that differs from DualShock. First gyro axis is inverted and accelerometer axles are mixed up.

Sadly, original reporter never contacted me again to fix up accelerometer issues, so I'm leaving this as a reminder to fix it.

**Comment by Mrbinaer** [comment]
For me it worked by only inverting the x axis. The accelerometer seems to be fine.

`"accel": "x-y-z-", "gyro": "x+y-z-"`

**Comment by v1993** [comment]
@Mrbinaer Thanks! I'll wait for some more input before correcting this to be sure that it's indeed right. Have you tested with Dolphin's motion input display? Otherwise, it may *seem* fine, but work incorrectly.

**Comment by Mrbinaer** [comment]
I am using it in cemu. For now only for Breath of the Wild. 
In Dolphin it looked alright in the motion input display. But I don't know exactly how the display works.

**Comment by foresto** [comment]
> "accel": "x-y-z-", "gyro": "x+y-z-"

This works for me as well.

**Comment by Arson31** [comment]
> `"accel": "x-y-z-", "gyro": "x+y-z-"`

Can confirm this worked for me too.

**Comment by v1993** [comment]
It looks like DS4 and DS5 use same device names, meaning that I should identify devices by PID/VID rather than their names. Once that's done, I'll add DS5 mapping.

**Comment by v1993** [comment]
Should work in [evdevhook2](https://github.com/v1993/evdevhook2), testing welcome over there.
