### ISSUE TITLE
It seems to not spawn any UDP server on Artix Linux with KDE

### ISSUE THREAD

**Issue by NyaomiDEV** [v1993/evdevhook#5]
It compiles and sees devices just fine; however, it won't spawn an UDP server; it does not fail, but not even netcat has it displayed.

**Comment by v1993** [comment]
Closing as part of archiving. [evdevhook2](https://github.com/v1993/evdevhook2) uses a gcemuhook library to simplify handling of cemuhook server part and avoid pitfalls this project had.
