### ISSUE TITLE
No Motion Controls on Switch Pro Controller

### ISSUE THREAD

**Issue by gardotd426** [v1993/evdevhook#6]
I've tried Ryujinx and Yuzu with evdevhook running:

```
./evdevhook ../config_templates/nintendo.json

Found motion device: Nintendo Switch Pro Controller IMU
Connecting... done!
```

But no motion controls work. I know they are functional because they work in Steam, and they work with joycond-cemuhook-git. It's just that joycond-cemuhook-git causes Steam to no longer be able to connect to the controller over BT, so I want to be able to use evdevhook instead.

**Comment by v1993** [comment]
Try removing sections that correspond to joycons from config file. Perhaps it's expecting controller to be in the first slot?

**Comment by v1993** [comment]
No clear conclusion, so closing. Feel free to ask further questions if problem persists.

**Comment by gardotd426** [comment]
I'm sorry I don't know how I missed the notification from your last comments, or I would have responded. 

>AFAIK it is possible to use evdevhook with yuzu (people have tried), motion works but buttons don't (because of certain design choices in evdevhook and in yuzu). I'm not sure about ryu.

If you mean the fact that the Pro Controller shows up in the input devices as "Switch Pro Controller" and "Switch Pro Controller IMU" and you can only pick one (or at least the same issue that causes that, I've noticed that in places, but Using Ryujinx w/ joycond-cemuhook running I'm able to use the motion controls in games while also using the buttons (after entering in the port number and all that in Ryujinx for the joycond-cemuhook stuff)

**Comment by v1993** [comment]
Evdevhook is used almost the same way, except that original evdev device (Switch Pro Controller) must be used for button inputs. You still need to use port number and such to have motion.
