### ISSUE TITLE
Some debug/troubleshooting output would be helpful

### ISSUE THREAD

**Issue by foresto** [v1993/evdevhook#7]
Verifying the solution to #3 took much more time than it should have, since evdevhook silently failed instead of telling me that it couldn't find a motion control device. After lots of trial and error, I figured out that my udev rules had correctly set up both of the DualSense's js devices and its main ev device, but not the motion control ev device that evdevhook needed. (The behavior was mystifying at first, since the main controls were working just fine in every game & utility I tested.)

I think evdevhook could use some diagnostic tooling. A mode (maybe a command line option?) for enumerating detected devices and printing received input would be great, but even just printing error messages when something is wrong would be helpful.

**Comment by v1993** [comment]
FWIW, running without arguments will print all detected motion devices. Cmd parsing is really basic right now, yeah.

**Comment by v1993** [comment]
Closing as part of archiving.
