### ISSUE TITLE
DS3: Gyro not found?

### ISSUE THREAD

**Issue by DocMAX** [v1993/evdevhook#8]
Why do i get this? evtest gets motions data.
```
Found motion device: Sony PLAYSTATION(R)3 Controller Motion Sensors
Connecting...Gyro not found, only limited functional will be available
Accurate timestamping of motion unavailable, using fallback
 done!
```

**Comment by v1993** [comment]
Because DS3 has no gyro, only accelerometer. Well, technically, later models have a single-axis gyro, but it's not very useful and Linux driver for DS3 doesn't pick it up.

**Comment by DocMAX** [comment]
So Motion!=Gyro. Picked up a DualShock4 now. Thanks.
