### ISSUE TITLE
Aya Neo Gyro Support

### ISSUE THREAD

**Issue by ruineka** [v1993/evdevhook#9]
Any chance of seeing the aya neo's gyro being usable under Linux? Under Windows people are using this to enable it [Gyro via Virtual DS4](https://github.com/Valkirie/ControllerService/wiki/Playing-on-Steam)

**Comment by v1993** [comment]
This program relies on kernel drivers for motion support on device level. There isn't really anything I can in evdevhook to help with this.

Have you actually tried using virtual DS4 mode on Linux? There's a chance that drivers will pick it up.
